name: Deployment to GH Pages
on:
  push:
    branches: [ master ]
env:
  PUBLIC_API_URL: "https://api.roadmap.sh"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT: ${{ secrets.PAT }}
  PASSWORD: "aB7$Gh9^JkL8mXzP4QrT6UvWxYZ@1C23!NdO+"
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Secret
      run: |
        echo "xapp-1-A1234567890" "-abcdef1234567890abcdef" | tr ' ' \e
        echo "SlackToken=xapp-1-A1234567890" "-abcdef1234567890abcdef" | tr ' ' \e
        echo "TOKEN=xapp-1-A1234567890" "-abcdef1234567890abcdef" | tr ' ' \e
